### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by TomWesterhof** [cmda-minor-vid/web-animation-18-19#1]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Tom Westerhof

## Class
VID 2

## About me
CMD-student die op dit moment de minor Visual Interface Design volgt

## Goals
Meer leren over HTML/CSS :)

## Skill level
Ik vind het erg leuk om te klooien met HTML/CSS/JS, maar ik kan niet zeggen dat ik een expert ben

## GitHub username
TomWesterhof

## GitHub repository
https://github.com/TomWesterhof/webanimaties

**Comment by dandevri** [comment]
👋 Tom, de link van je repo staat in m'n admin sheet!

**Comment by dandevri** [comment]
Wel nog een beetje leeg :(
