### ISSUE TITLE
Introduction Mike van den Bos

### ISSUE THREAD

**Issue by stefmike12** [cmda-minor-vid/web-animation-18-19#10]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
**Mike** van den Bos

## Class
VID2

## About me
Write something about yourself: 

> **_something about yourself_**

## Goals
Mooie animaties kunnen maken en Github begrijpen

## Skill level
⭑⭒⭒⭒⭒

## GitHub username
[Mike's Github](https://github.com/stefmike12)

## GitHub repository
[Mike's Github repository](https://github.com/stefmike12/webanimation)

**Comment by dandevri** [comment]
👋 Mike, de link van je repo staat in m'n admin sheet! 

Wel beetje leeg nog wel :(

**Comment by stefmike12** [comment]
Danny, als ik het goed heb gedaan staat er nu wel wat!

**Comment by dandevri** [comment]
Yes 🎉
