### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Agunovvski** [cmda-minor-vid/web-animation-18-19#11]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Agung Tarumampen`

## Class
`VID 1`

## About me
`I am 20 years old studying CMD specialising in UI and UX who also likes to code once in a while`

## Goals
`Challenge my skillset in CSS(also JS), write more semantic code and expand my knowledge`

## Skill level
`Advanced`

## GitHub username
`https://github.com/Agunovvski`

## GitHub repository
`https://github.com/Agunovvski/webanimaties`

**Comment by dandevri** [comment]
👋 Agung, de link van je repo staat in m'n admin sheet!
