### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by BrianJakobs** [cmda-minor-vid/web-animation-18-19#12]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Brian Jakobs`

## Class
`Vid 2`

## About me
`My name is Brian Jakobs, I like watching movies and playing video games... the usual stuff. Besides the usual stuff, I also like make illustrations and I'm passionate about animation. I like to become a good Visual Designer and illustrator with a good understanding of animation, both web animations and normal digital animations.`

## Goals
`For this class I would like to use a new CSS3 feature, so I have to force myself to learn new things. I also want to manipulate a SVG file and use it to animate. Besides these two thing I also want to keep my code as clean as possible so that someone who is on the same skill level as I am can still understand my code.`

## Skill level
`I would say my skill level is between intermediate and advanced. I have some experience with HTML, CSS and JS but I wouldn't say I am fully advanced. Besides the standard coding classes, I have also followed the class 'Frontend voor Designers' which was about using JS for interaction.`

## GitHub username
`My GitHub username is BrianJakobs and my GitHub page is: https://github.com/BrianJakobs`

## GitHub repository
`https://github.com/BrianJakobs/HTML-CSS`

**Comment by dandevri** [comment]
👋 Brian, de link van je repo staat in m'n admin sheet! Je kan nog gh-pages aanzetten en de link delen in de readme / description van je repo.

Welke video games speel je? 🎮
