### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by AnneWS** [cmda-minor-vid/web-animation-18-19#13]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Anne-Wil Sikma`

## Class
`VID2`

## About me
`hi`

## Goals
`Beter worden in animaties door middel van CSS, waarbij ze er ook nog goed uitzien en werken.`

## Skill level
`Intermediate, heb wel een aantal klassen gehad waarbij je door middel van CSS een animatie moest maken.`

## GitHub username
`https://github.com/AnneWS`

## GitHub repository
`https://github.com/AnneWS/VID2Webanimaties`

**Comment by dandevri** [comment]
👋 Anne-Wil, de link van je repo staat in m'n admin sheet! Je kan gh-pages nog aanzetten en de link delen in de readme / description van je repo.
