### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Mireilleegberts** [cmda-minor-vid/web-animation-18-19#14]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Mireille Egberts`

## Class
`VID1`

## About me
`Mij maak je blij met toffe webdesign en interacties. `

## Goals
`Meer met animaties te kunnen doen in CSS`

## Skill level
`intermediate, ik weet me aardig te redden met HTML,CSS)`

## GitHub username
https://github.com/Mireilleegberts

## GitHub repository
https://github.com/Mireilleegberts/Vak-Webanimaties

**Comment by dandevri** [comment]
👋 Mireille, de link van je repo staat in m'n admin sheet!

Wel beetje leeg nog wel :(
