### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by kirstenpropitius** [cmda-minor-vid/web-animation-18-19#15]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Kirsten Propitius`

## Class
`VID1`

## About me
`Ik hou heel erg van vormgeven/designen, hier zou ik later ook graag wat mee willen doen. Het zelf coderen vind ik wel wat lastiger maar leuk om te doen.`

## Goals
`Ik zou tijdens dit vak graag mijn niveau van HTML en CSS willen verbeteren. Ik zou aan het eind van dit vak het niveau willen hebben om met HTML en CSS coole animaties te kunnen maken`

## Skill level
`intermediate, de basis van HTML en CSS moet wel lukken.`

## GitHub username
`https://github.com/Kirstenpropitius`

## GitHub repository
`https://github.com/kirstenpropitius/HTML-CSS`

**Comment by dandevri** [comment]
👋 Kirsten, de link van je repo staat in m'n admin sheet!

Wel beetje leeg nog wel :(
