### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by henkwillem** [cmda-minor-vid/web-animation-18-19#16]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Henk Willem de Boer 

## Class
Visual Interface Design 2

## About me
Focus on Visual and UI/UX Design

## Goals
Getting better at coding and having fun with it

## Skill level
Beginner, but want to become better.

## GitHub username
https://github.com/henkwillem

## GitHub repository
https://github.com/henkwillem?tab=repositories

**Comment by dandevri** [comment]
👋 Henk Willem, ik kan de repo voor dit vak niet vinden tussen je repository's?

**Comment by henkwillem** [comment]
Hey Danny, als het goed is kun je hem nu wel zien.

**Comment by dandevri** [comment]
Ik zie een `fork` van de originele repository maar niet je eigen code. Je kan het beste denk ik een nieuwe aparte Repo op github aanmaken.
