### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by AngelaMastenbroek** [cmda-minor-vid/web-animation-18-19#17]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Angela Mastenbroek

## Class
VID2

## About me
Ik kan met HTML CSS werken maar heb hier wel moeite mee.

## Goals
Basis van HTML en CSS bijwerken en hier meer over leren en animaties leren coderen. 

## Skill level
Beginner

## GitHub username
https://github.com/AngelaMastenbroek

## GitHub repository
https://github.com/AngelaMastenbroek/Web-Animation

**Comment by dandevri** [comment]
👋 Angela, de link van je repo staat in m'n admin sheet!

Kom het vooral vragen als iets niet lukt! ❓
