### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by KayleeRoxanne** [cmda-minor-vid/web-animation-18-19#18]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Kaylee Hoogerhout

## Class
VID2

## About me
Ik ben CMD student, waarbij ik mij vooral richt op visual en ux/ui design. De gehele opleiding ben ik op zoek geweest, naar wat ik leuk vind in dit vakgebied. 

## Goals
Tijdens dit vak hoop ik nieuwe visuele ontwerpen te kunnen maken en dit te kunnen overbrengen in code, vanuit mijn basiskennis. 

## Skill level
Intermediate, omdat ik de basiskennis over code heb, alleen ligt het mij niet 

## GitHub username
https://github.com/KayleeRoxanne

## GitHub repository
https://github.com/KayleeRoxanne/webAnimatie

**Comment by dandevri** [comment]
👋 Kaylee, de link van je repo staat in m'n admin sheet!
