### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by SanneKrutzen** [cmda-minor-vid/web-animation-18-19#19]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Sanne Krutzen`

## Class
`Vid2`

## About me
`Ik volg CMD aan de Haagse Hogeschool en doe deze minor om een breder perspectief te krijgen op het gebied van de mogelijkheden in interface design.`

## Goals
`De mogelijkheden en limitaties van het coderen leren te begrijpen zodat ik dat mee kan nemen in het maken van een ontwerp.`

## Skill level
`Intermediate`

## GitHub username
`https://github.com/SanneKrutzen`

## GitHub repository
`https://sannekrutzen.github.io/webAnimaties/`

**Comment by dandevri** [comment]
👋 Sanne, de link van je repo staat in m'n admin sheet!
