### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by TristanGalavazi** [cmda-minor-vid/web-animation-18-19#2]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Tristan Galavazi`

## Class
`VID2`

## About me
`I'm a student from MIC (Media, Informatie en Communicatie) following the CMD minor Visual Interface Design. I have never coded or wrote HTML or CSS before. Nonetheless I always admired people who can code and create cool things with it. My abilities lie more in visualizing and creating content with an eye for detail. 
Last week/month I've been doing some course at FreeCodeCamp for basic HTML and CSS to gain some basic knowledge for this class and future projects. A.t.m. I'm still finishing the 14 chapters on Interneting is Hard which I find very useful but also already complex.`

## Goals
`I want to try and get a better understanding of the basic principles of HTML and CSS and also create something with it according to the assignment for this class. Besides I never programmed or coded before I want to give my best and do anything I can, from self learning from internet and asking classmates and with the lectures of the teacher, I want to pass this assignment in one go with a satisfying result where I also developed my basic coding skills.
I also want to be able to understand the basic rules of HTML and CSS so whenever I see a bunch of coding in some front-end content I won't be surprised and lost anymore but I can understand the main rules and principles.`

## Skill level
`Beginner level.`

## GitHub username
`https://github.com/TristanGalavazi`

## GitHub repository
`https://github.com/TristanGalavazi/Opslag`

**Comment by dandevri** [comment]
👋 Tristan, de link van je repo staat in m'n admin sheet!

**Comment by dandevri** [comment]
Wel nog een beetje leeg :(
