### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by brittrademaker** [cmda-minor-vid/web-animation-18-19#20]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Britt

## Class
VID1

## About me
Ik hoop met deze minor meer kennis te ontwikkelen voor mijn passie, (visual) design

## Goals
Meer leren over HTML/CSS zodat ik die toffe kennis kan gebruiken om een/mijn droom portfolio te maken ;)

## Skill level
Beginner - intermediate

## GitHub username
https://github.com/brittrademaker

## GitHub repository
https://github.com/brittrademaker/artwork-brittrademaker

**Comment by brittrademaker** [comment]
https://brittrademaker.github.io/artwork-brittrademaker/index.html

**Comment by dandevri** [comment]
Thanks! 🎉
