### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by celinevl** [cmda-minor-vid/web-animation-18-19#21]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Céline

## Class
VID1

## About me
`Write something about yourself`

## Goals
`Mijn geheugen weer opfrissen, oefenen en meer leren over html/css (javascript) wat ik voor later weer kan gebruiken. (En een eindresultaat die ik misschien wel aan mijn portfolio toe zou kunnen voegen..)`

## Skill level
`Net iets meer dan een beginner?`

## GitHub username
https://celinevl.github.io/webanimations/

## GitHub repository
https://github.com/celinevl/webanimations

**Comment by dandevri** [comment]
Thanks! 🎉
