### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by jimmykuik** [cmda-minor-vid/web-animation-18-19#22]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Jimmy

## Class
VID1

## About me
Part-time visual designer. Ik hoop mijn kennis te kunnen verbreden in deze minor.

## Goals
Meer leren over het gebruik van html/css in combinatie met javascript. Voornamelijk het javascript deel probeer ik meer onder de knie te krijgen.

## Skill level
Beginner

## GitHub username
https://github.com/jimmykuik

## GitHub repository
https://github.com/jimmykuik/webanimations

**Comment by dandevri** [comment]
Thanks! 🎉
