### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by henkwillem** [cmda-minor-vid/web-animation-18-19#23]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Henk Willem de Boer

## Class
VID2

## About me
I'm not a nerd, but i want to become better at coding :)

## Goals
Getting better at coding as mentioned before.

## Skill level
Beginner, i'm not really into coding but i think it is an important skill to develop when you want to become a good designer.

## GitHub username
www.github.com/henkwillem

## GitHub repository
https://github.com/henkwillem/web-animation-18-19

**Comment by dandevri** [comment]
Thanks! 🎉
