### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Floris97** [cmda-minor-vid/web-animation-18-19#3]
# My Introduction

I'm Floris Elders.  ¯\_(ツ)_/¯

## Name
`Floris Elders`

## Class
`VID1`

## About me
`In my free time I like to workout, watch netflix, drink some drenk and chill with friends and last but not least design awesome things!`

## Goals
`get and better understanding of what you can do with Css transitions in the browser.`

## Skill level
`Somewhere between beginner - intermediate`

## GitHub username
`https://github.com/Floris97`

## GitHub repository
`https://github.com/Floris97/Web-Animatie`

**Comment by dandevri** [comment]
👋 Floris, de link van je repo staat in m'n admin sheet!
