### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by dianaphs** [cmda-minor-vid/web-animation-18-19#4]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Diana Nguyen`

## Class
`VID2`

## About me
`CMD studente die momenteel de minor Visual Interface Design volgt`

## Goals
`Het zou mooi zijn als ik na deze minor kan zeggen dat ik beter ben geworden in HTML/CSS/JS`

## Skill level
`Ik zou zeggen dat mijn skill level nog op beginner niveau is. Er is niet veel blijven hangen na het propedeuse jaar omdat ik UX en visual design interessanter vind. (Dit betekent trouwens niet dat ik niet open sta om HTML/CSS/JS weer op te pakken ;))`

## GitHub username
`https://github.com/dianaphs`

## GitHub repository
`https://github.com/dianaphs/web-animation`

**Comment by dandevri** [comment]
👋 Diana, de link van je repo staat in m'n admin sheet!

**Comment by dandevri** [comment]
Je zou gh-pages nog even aan kunnen zetten en de live link in je readme / description zetten.
