### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Joopakerboom** [cmda-minor-vid/web-animation-18-19#5]
# My Introduction

*An introduction of me for the course: Web Animation.*

## Name
`Joop Akerboom`

## Class
`VID2`

## About me
`I'm an enthusiastic visual branding and UI designer, which I try to combine with animation. My strength lies in the level of detail in the visual cases.`

## Goals
`My goals for this class are refining my transition and animation skills to create a coherent experience for users to experience. Besides that, I would like to develop a own sense of style where I can approach possible clients with.  `

## Skill level
`Between intermediate and advanced. But I'm a geek in pointless details.`

## GitHub username
`https://github.com/Joopakerboom`

## GitHub repository
`https://github.com/Joopakerboom/web-animation`

**Comment by dandevri** [comment]
👋  Joop, de link van je repo staat in m'n admin sheet!
