### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by JanneJansen** [cmda-minor-vid/web-animation-18-19#6]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Janne Jansen

## Class
VID1

## About me
Student product design aan de HVA 

## Goals
Het onder de knie krijgen van HTML en CSS.

## Skill level
beginner

## GitHub username
@JanneJansen

## GitHub repository
https://github.com/JanneJansen?tab=repositories

**Comment by dandevri** [comment]
👋 Janne, ik kan de repo met je code niet helemaal vinden. Wil dat een beetje lukken?

**Comment by JanneJansen** [comment]
Hi,
Ik snapte dat nog niet helemaal maar ga het morgen wel even regelen. Ga er
morgen met Gizing en Sam aan zitten dus moet goed komen.
Thanks!

Op dinsdag 14 mei 2019 schreef Danny de Vries <notifications@github.com>:
