### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by jslikker02** [cmda-minor-vid/web-animation-18-19#7]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Jay-Jay Slikker`

## Class
`VID 2`

## About me
`Ik ben een CMD student die zich vooral op UX gericht heeft maar wel altijd uitstapjes maakt met bijvoorbeeld het vak frontend for designers en nu de Minor visual interface design om zo allround mogelijk te zijn. `

## Goals
`Ik hoop dat code wat natuurlijker voor mij gaat voelen en niet constant als een uitdaging zodat ik het wellicht ook eerder toepas in bijvoorbeeld prototypes`

## Skill level
`Nou een beginner ben ik uiteraard niet meer als 3e jaars cmd student, echter heb ik wel vaak nog moeite met coderen dus ik zit tussen de beginner en het gemiddelde in denk ik `

## GitHub username
`https://github.com/jslikker02 `

## GitHub repository
`https://github.com/jslikker02/webanimaties`

**Comment by dandevri** [comment]
👋 Jay-Jay, de link van je repo staat in m'n admin sheet!

Wel beetje leeg nog :(
