### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by GKhalandi** [cmda-minor-vid/web-animation-18-19#8]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Gizing Khalandi

## Class
VID1

## About me
Ik volg momenteel de minor Visual Interface Design om meer te leren over Visual. 

## Goals
Om meer te leren over Javascript en animaties in het web. En vaker uit mijn comfortzone te komen met coderen van moeilijke opgaves. 

## Skill level
beginner / intermediate

## GitHub username
GKhalandi

## GitHub repository
https://github.com/GKhalandi

**Comment by dandevri** [comment]
👋 Gizing, ik kan de repo voor dit vak niet vinden tussen je repository's?

**Comment by GKhalandi** [comment]
Hi Danny, 

Ik zie dat ik de verkeerde heb opgegeven. Dit is als het goed is de juiste repository. :)

https://github.com/GKhalandi/Gkhalandi.github.io
