### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by batuhanarican** [cmda-minor-vid/web-animation-18-19#9]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Batuhan`

## Class
`VID1`

## About me
`I like coffee, graphic design, coding, drawing and also coffee.`

## Goals
`I want to learn to manipulate and animate SVG code properly.`

## Skill level
`Intermediate`

## GitHub username
`https://github.com/batuhanarican`

## GitHub repository
`https://github.com/batuhanarican/html-css`
`https://batuhanarican.github.io/html-css/`

**Comment by dandevri** [comment]
👋 Batuhan, de link van je repo staat in m'n admin sheet! Je zou gh-pages nog aan kunnen zetten en de live link delen.

Wat is je favoriete koffie brewing method? ☕️

**Comment by batuhanarican** [comment]
Ik heb het aangepast en mijn page link toegevoegd! En mijn favoriete coffee brewing method is gewoon simpel van een espresso machine :)

Met vriendelijke groet,

Batuhan Arican

Op 14 mei 2019, om 13:56 heeft Danny de Vries <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


👋 Batuhan, de link van je repo staat in m'n admin sheet! Je zou gh-pages nog aan kunnen zetten en de live link delen.

Wat is je favoriete koffie brewing method? ☕️
